name: Docker Workflow
on:
  push:
    paths:
      - '**.java'
  workflow-dispatch:
jobs:
  build_Docker_image:
    name: Push Docker image to Docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Echo Test
        run: echo This is a test